packages:
  - packages/*

catalog:
  "@eslint/js": ^9.29.0
  "@hono/node-server": ^1.14.4
  "@storybook/addon-docs": ^9.0.13
  "@storybook/angular": ^9.0.13
  "@tailwindcss/postcss": ^4.1.11
  "@types/node": ^24.0.4
  "@typescript/native-preview": 7.0.0-dev.20250620.1
  argon2: ^0.43.0
  clsx: ^2.1.1
  date-fns: ^4.1.0
  dotenv: ^17.2.0
  eslint: ^9.29.0
  eslint-plugin-storybook: ^9.0.13
  hono: ^4.7.11
  jose: ^6.0.11
  kysely: ^0.28.2
  postcss: ^8.5.6
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  storybook: ^9.0.13
  typescript-eslint: ^8.34.0
  tailwindcss: ^4.1.11
  tailwind-merge: ^3.3.1
  typescript: ^5.8.3
  tsx: ^4.20.3
  uuid: ^11.1.0
  vitest: ^3.2.4
  zod: ^3.25.67
  zx: ^8.6.0

onlyBuiltDependencies:
  - "@compodoc/compodoc"
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - argon2
  - better-sqlite3
  - esbuild
  - lmdb
  - msgpackr-extract

nodeLinker: hoisted
