/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Blog {
  author_id: string;
  content: string;
  created_at: Generated<number>;
  id: string;
  image: string | null;
  summary: string;
  title: string;
  updated_at: Generated<number>;
}

export interface InvalidatedSessions {
  exp: number;
  jwt_hash: string;
}

export interface User {
  id: string;
  name: string;
  password: string;
  username: string;
}

export interface DB {
  blog: Blog;
  invalidated_sessions: InvalidatedSessions;
  user: User;
}
